services:
  llm:
    extends:
      file: ./docker/services.compose.yml
      service: llm
  translator-backend:
    extends:
      file: ./docker/services.compose.yml
      service: translator-backend
    ports:
      - "8000:8000"
